name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  whisper-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        pytorch-version: [1.13.1, 2.0.0]
        exclude:
          - python-version: '3.11'
            pytorch-version: 1.13.1
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -n test ffmpeg python=${{ matrix.python-version }}
      - run: pip3 install torch==${{ matrix.pytorch-version }}+cpu --index-url https://download.pytorch.org/whl/cpu
      - uses: actions/checkout@v3
      - run: echo "$CONDA/envs/test/bin" >> $GITHUB_PATH
      - run: pip install .["dev"]
      - run: black --check --diff -t py38 --include '(\.pyi?)$' .
      - run: isort --check --diff .
      - run: flake8 --ignore E203,W503,W504,E501,E731,E741 .
      - run: pytest --durations=0 -vv -k 'not test_transcribe or test_transcribe[tiny] or test_transcribe[tiny.en]' -m 'not requires_cuda'
